INSERT INTO universities(Jagiellonian University); 
INSERT INTO universities(University of Warsaw); 
INSERT INTO universities(Wroclaw Medical University); 
INSERT INTO universities(Medical University of Lodz); 
INSERT INTO universities(Adam Mickiewicz University, Poznań); 
INSERT INTO universities(AGH University of Krakow); 
INSERT INTO universities(Gdańsk University of Technology); 
INSERT INTO universities(Medical University of Bialystok); 
INSERT INTO universities(Medical University of Gdańsk); 
INSERT INTO universities(Medical University of Warsaw); 
INSERT INTO universities(Nicolaus Copernicus University in Toruń); 
INSERT INTO universities(Poznan University of Medical Sciences); 
INSERT INTO universities(SWPS University of Social Sciences and Humanities); 
INSERT INTO universities(University of Wrocław); 
INSERT INTO universities(University of Gdańsk); 
INSERT INTO universities(The John Paul II Catholic University of Lublin); 
INSERT INTO universities(Lodz University of Technology); 
INSERT INTO universities(Medical University of Lublin); 
INSERT INTO universities(Medical University of Silesia in Katowice); 
INSERT INTO universities(Opole University of Technology); 
INSERT INTO universities(Poznań University of Life Sciences); 
INSERT INTO universities(Poznan University of Technology); 
INSERT INTO universities(Silesian University of Technology); 
INSERT INTO universities(Warsaw University of Life Sciences – SGGW); 
INSERT INTO universities(Warsaw University of Technology); 
INSERT INTO universities(Wrocław University of Environmental and Life Sciences); 
INSERT INTO universities(Wrocław University of Science and Technology); 
INSERT INTO universities(Bialystok University of Technology); 
INSERT INTO universities(Cracow University of Technology); 
INSERT INTO universities(Jan Kochanowski University in Kielce); 
INSERT INTO universities(University of Life Sciences in Lublin); 
INSERT INTO universities(University of Łódź); 
INSERT INTO universities(Maria Curie-Skłodowska University (UMCS)); 
INSERT INTO universities(Rzeszów University of Technology); 
INSERT INTO universities(SGH Warsaw School of Economics); 
INSERT INTO universities(University of Silesia in Katowice); 
INSERT INTO universities(University of Warmia and Mazury in Olsztyn); 
INSERT INTO universities(Maritime University of Szczecin); 
INSERT INTO universities(WSB Academy); 
