INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (0, 708, 'Uniwersytet Jagielloński', true, '/world-university-rankings/jagiellonian-university', 19.9328982, 50.0610645, 'Gołębia 24, 31-007 Kraków, Polska', 'Kraków', 34309); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (0, 'Education'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (1, 820, 'Uniwersytet Warszawski', true, '/world-university-rankings/university-warsaw', 21.0186012, 52.2403463, 'Krakowskie Przedmieście 26/28, 00-927 Warszawa, Polska', 'Warszawa', 34342); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (1, 'Literature & Linguistics'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (2, 765, 'Uniwersytet Medyczny im. Piastów Śląskich we Wrocławiu', true, '/world-university-rankings/wroclaw-medical-university', 17.0688865, 51.1089147, 'Rektorat, wybrzeże Ludwika Pasteura 1, 50-367 Wrocław, Polska', 'Wrocław', 8014); 
INSERT INTO universities_subjects(u_id, subject) VALUES (2, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (2, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (2, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (2, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (2, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (2, 'Other Health'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (3, 991, 'Uniwersytet Medyczny w Łodzi', false, '/world-university-rankings/medical-university-lodz-0', 19.454088, 51.769881, 'al. Tadeusza Kościuszki 4, 90-419 Łódź, Polska', 'Łódź', 10237); 
INSERT INTO universities_subjects(u_id, subject) VALUES (3, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (3, 'Other Health'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (4, 613, 'Uniwersytet im. Adama Mickiewicza w Poznaniu', false, '/world-university-rankings/adam-mickiewicz-university-poznan', 16.9154021, 52.4083974, 'Wieniawskiego 1, 61-712 Poznań, Polska', 'Poznań', 33268); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (4, 'Education'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (5, 713, 'Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie', false, '/world-university-rankings/agh-university-krakow', 19.9232752, 50.06448229999999, 'al. Adama Mickiewicza 30, 30-059 Kraków, Polska', 'Kraków', 19189); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (5, 'Civil Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (6, 961, 'Politechnika Gdańska', true, '/world-university-rankings/gdansk-university-technology', 18.6163277, 54.3716751, 'Gabriela Narutowicza 11/12, 80-233 Gdańsk, Polska', 'Gdańsk', 13903); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (6, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (7, 705, 'Uniwersytet Medyczny w Białymstoku', true, '/world-university-rankings/medical-university-bialystok', 23.1653094, 53.13058119999999, 'Jana Kilińskiego 1, 15-089 Białystok, Polska', 'Białystok', 5705); 
INSERT INTO universities_subjects(u_id, subject) VALUES (7, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (7, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (7, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (7, 'Other Health'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (8, 940, 'Gdański Uniwersytet Medyczny', false, '/world-university-rankings/medical-university-gdansk', 18.6228077, 54.3659002, 'Marii Skłodowskiej-Curie 3a, 80-210 Gdańsk, Polska', 'Gdańsk', 6340); 
INSERT INTO universities_subjects(u_id, subject) VALUES (8, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (8, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (8, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (8, 'Medicine & Dentistry'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (9, 634, 'Warszawski Uniwersytet Medyczny', true, '/world-university-rankings/medical-university-warsaw', 20.983059, 52.2076428, 'Żwirki i Wigury 61, 02-091 Warszawa, Polska', 'Warszawa', 10068); 
INSERT INTO universities_subjects(u_id, subject) VALUES (9, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (9, 'Other Health'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (10, 666, 'Uniwersytet Mikołaja Kopernika', false, '/world-university-rankings/nicolaus-copernicus-university-torun', 18.5711994, 53.0195187, 'Jurija Gagarina 11, 87-100 Toruń, Polska', 'Toruń', 18122); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Veterinary Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (10, 'Accounting & Finance'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (11, 989, 'Uniwersytet Medyczny im. Karola Marcinkowskiego w Poznaniu', true, '/world-university-rankings/poznan-university-medical-sciences', 16.918381, 52.4097395, 'Collegium Maius, Fredry 10, 61-701 Poznań, Polska', 'Poznań', 7296); 
INSERT INTO universities_subjects(u_id, subject) VALUES (11, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (11, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (11, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (11, 'Medicine & Dentistry'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (12, 878, 'Uniwersytet SWPS', false, '/world-university-rankings/swps-university-social-sciences-and-humanities', 21.0659662, 52.2483911, 'Chodakowska 19/31, 03-815 Warszawa, Polska', 'Warszawa', 15863); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (12, 'Law'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (13, 779, 'Uniwersytet Wrocławski', true, '/world-university-rankings/university-wroclaw', 17.034463, 51.1140053, 'plac Uniwersytecki 1, 50-137 Wrocław, Polska', 'Wrocław', 17787); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (13, 'Business & Management'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (14, 801, 'Uniwersytet Gdański', false, '/world-university-rankings/university-gdansk', 18.5743202, 54.3961355, 'Jana Bażyńskiego 8, 80-309 Gdańsk, Polska', 'Gdańsk', 18961); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (14, 'Business & Management'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (15, 635, 'Katolicki Uniwersytet Lubelski Jana Pawła II', true, '/world-university-rankings/john-paul-ii-catholic-university-lublin', 22.5450221, 51.2475453, 'Aleje Racławickie 14, 20-950 Lublin, Polska', 'Lublin', 9173); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (15, 'Sociology'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (16, 847, 'Politechnika Łódzka', true, '/world-university-rankings/lodz-university-technology', 19.4517176, 51.7537146, 'Stefana Żeromskiego 116, 90-924 Łódź, Polska', 'Łódź', 11706); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (16, 'Electrical & Electronic Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (17, 983, 'Collegium Novum; Uniwersytet Medyczny w Lublinie', true, '/world-university-rankings/medical-university-lublin-0', 22.5488293, 51.2481722, 'Aleje Racławickie 1, 20-059 Lublin, Polska', 'Lublin', 6884); 
INSERT INTO universities_subjects(u_id, subject) VALUES (17, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (17, 'Other Health'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (18, 604, 'Śląski Uniwersytet Medyczny w Katowicach', false, '/world-university-rankings/medical-university-silsia-0', 19.0102821, 50.2510603, 'Poniatowskiego 15, 40-055 Katowice, Polska', 'Katowice', 10237); 
INSERT INTO universities_subjects(u_id, subject) VALUES (18, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (18, 'Other Health'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (19, 688, 'Politechnika Opolska', false, '/world-university-rankings/opole-university-technology', 17.9050435, 50.65411719999999, 'Prószkowska 76, 45-758 Opole, Polska', 'Opole', 5096); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (19, 'Business & Management'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (20, 838, 'Uniwersytet Przyrodniczy', false, '/world-university-rankings/poznan-university-life-sciences', 16.9042848, 52.4271447, 'Wojska Polskiego 28, 60-637 Poznań, Polska', 'Poznań', 6184); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (20, 'Veterinary Science'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (21, 612, 'Politechnika Poznańska', true, '/world-university-rankings/poznan-university-technology', 16.91838, 52.3941095, 'plac Marii Skłodowskiej-Curie 5, 60-965 Poznań, Polska', 'Poznań', 14304); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (21, 'General Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (22, 763, 'Politechnika Śląska', true, '/world-university-rankings/silesian-university-technology', 18.6746196, 50.2909719, 'Akademicka 2A, 44-100 Gliwice, Polska', 'Gliwice', 17424); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (22, 'Civil Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (23, 621, 'Szkoła Główna Gospodarstwa Wiejskiego w Warszawie', true, '/world-university-rankings/warsaw-university-life-sciences-sggw', 21.0463478, 52.1635854, 'Nowoursynowska 166, 02-787 Warszawa, Polska', 'Warszawa', 15737); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Veterinary Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (23, 'Business & Management'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (24, 977, 'Politechnika Warszawska', false, '/world-university-rankings/warsaw-university-technology', 21.0080857, 52.2212012, 'plac Politechniki 1, 00-661 Warszawa, Polska', 'Warszawa', 23167); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (24, 'Earth & Marine Sciences'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (25, 607, 'Uniwersytet Przyrodniczy we Wrocławiu', true, '/world-university-rankings/wroclaw-university-environmental-and-life-sciences', 17.064267, 51.11142299999999, 'Norwida 25, 50-375 Wrocław, Polska', 'Wrocław', 7099); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Veterinary Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (25, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (26, 827, 'Politechnika Wrocławska', false, '/world-university-rankings/wroclaw-university-science-and-technology', 17.0625052, 51.1077469, 'wybrzeże Stanisława Wyspiańskiego 27, 50-370 Wrocław, Polska', 'Wrocław', 22772); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (26, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (27, 877, 'Politechnika Białostocka', true, '/world-university-rankings/bialystok-university-technology', 23.1465921, 53.11621239999999, 'Wiejska 45A, 15-351 Białystok, Polska', 'Białystok', 6471); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (27, 'Computer Science'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (28, 877, 'Politechnika Krakowska im. Tadeusza Kościuszki', true, '/world-university-rankings/cracow-university-technology', 19.9427642, 50.0720447, 'Warszawska 24, 31-155 Kraków, Polska', 'Kraków', 13510); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (28, 'Computer Science'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (29, 673, 'Uniwersytet Jana Kochanowskiego w Kielcach', false, '/world-university-rankings/jan-kochanowski-university-kielce', 20.6375151, 50.866608, 'Stefana Żeromskiego 5, 25-369 Kielce, Polska', 'Kielce', 10010); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (29, 'Chemistry'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (30, 753, 'Università di Scienze di Lublino', true, '/world-university-rankings/university-life-sciences-lublin', 22.5401097, 51.24372469999999, 'Akademicka 13, 20-400 Lublin, Polska', 'Lublin', 7355); 
INSERT INTO universities_subjects(u_id, subject) VALUES (30, 'Veterinary Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (30, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (30, 'Agriculture & Forestry'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (31, 645, 'Uniwersytet Łódzki', false, '/world-university-rankings/university-lodz', 19.4746328, 51.77254500000001, 'ul. Prez, Prezydenta Gabriela Narutowicza 68, 90-136 Łódź, Polska', 'Łódź', 21633); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (31, 'Sociology'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (32, 849, 'Uniwersytet Marii Curie-Skłodowskiej', true, '/world-university-rankings/maria-curie-sklodowska-university-umcs', 22.5408742, 51.2455041, 'ul. Marii Curie-Skłodowskiej 5, 20-400 Lublin, Polska', 'Lublin', 16937); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Archaeology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (32, 'Accounting & Finance'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (33, 935, 'Politechnika Rzeszowska im. Ignacego Łukasiewicza', true, '/world-university-rankings/rzeszow-university-technology', 21.989195, 50.019034, 'Aleja Powstańców Warszawy 12, 35-959 Rzeszów, Polska', 'Rzeszów', 10742); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Chemical Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (33, 'Accounting & Finance'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (34, 622, 'Szkoła Główna Handlowa w Warszawie', true, '/world-university-rankings/sgh-warsaw-school-economics', 21.0087369, 52.2089374, 'al. Niepodległości 162, 02-554 Warszawa, Polska', 'Warszawa', 8618); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (34, 'Accounting & Finance'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (35, 823, 'Uniwersytet Śląski w Katowicach', true, '/world-university-rankings/university-silesia-katowice', 19.0280936, 50.2607465, 'Bankowa 12, 40-007 Katowice, Polska', 'Katowice', 19222); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Geography'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (35, 'Physics & Astronomy'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (36, 867, 'Uniwersytet Warmińsko-Mazurski w Olsztynie', false, '/world-university-rankings/university-warmia-and-mazury-olsztyn', 20.4608081, 53.7601848, 'Michała Oczapowskiego 2, Olsztyn, Polska', 'Olsztyn', 16899); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Veterinary Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Art'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Performing Arts & Design'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Politics & International Studies (incl Development Studies)'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Geology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Environmental'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Earth & Marine Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Agriculture & Forestry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Biological Sciences'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Physics & Astronomy'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'History'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Philosophy & Theology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Communication & Media Studies'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Sport Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Medicine & Dentistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Architecture'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Law'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Mathematics & Statistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Chemistry'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Psychology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Sociology'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (36, 'Accounting & Finance'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (37, 956, 'Politechnika Morska w Szczecinie', true, '/world-university-rankings/maritime-university-szczecin', 14.5636405, 53.42887109999999, 'Wały Chrobrego 1/2, 70-500 Szczecin, Polska', 'Szczecin', 2484); 
INSERT INTO universities_subjects(u_id, subject) VALUES (37, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (37, 'Electrical & Electronic Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (37, 'General Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (37, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (37, 'Mechanical & Aerospace Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (37, 'Business & Management'); 
INSERT INTO universities(id, rank, name, academic, url, lng, lat, address, city, number_students) VALUES (38, 949, 'Akademia WSB w Dąbrowie Górniczej', false, '/world-university-rankings/wsb-academy', 19.19177, 50.32647100000001, 'Zygmunta Cieplaka 1c, 41-300 Dąbrowa Górnicza, Polska', 'Dąbrowa Górnicza', 4682); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Computer Science'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Accounting & Finance'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Economics & Econometrics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Other Health'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Civil Engineering'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Languages'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Literature & Linguistics'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Education'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Business & Management'); 
INSERT INTO universities_subjects(u_id, subject) VALUES (38, 'Sociology'); 
